#
#                ZIPO 
#
#             ZIPOLIB  MAKFILE



LIB_PATH= $(ROOT)/lib.dbg/$(PF)
SRC_PATH= $(ROOT)/zipolib/src
INC_PATH= $(ROOT)
TGT= libzipo.a



$(TGT) : $(OBJS)
	ar cru	$(TGT)  $(OBJS) $(CPPOBJS)
	mv 	$(TGT) $(LIB_PATH)/$(TGT)

	
	
allcpp:
	rm -f all.cpp
	touch all.cpp
	@for file in $(CFILES); do \
		echo "#include<$$file>" >> all.cpp; \
	done

include $(ROOT)/Makefile.common
CFLAGS+=-DDEBUG=1  -DPROFILING
.PHONY : freebsd install

	
